### ISSUE TITLE
Update hook isn't working

### ISSUE THREAD

**Issue by dacz** [nassor/mongoose-history#25]
Installed version from npm.
Save works ok. Update doesn't work.
Reviewed code and I see that in github there is version with update code but downloaded npm package has no update code.
Thanks!

**Comment by Jan-Bart** [comment]
Updating was fixed in ee630c4f5f5c60c10ceecc3b2941e2c7a7ab7bda but then reverted by @nassor

**Comment by dacz** [comment]
I saw reverting issue… so currently no update yer, right?

**Comment by Jan-Bart** [comment]
I'm afraid so.

**Comment by nassor** [comment]
The "update" functionality had some lock problems.

I'm rewriting the tests and part (almost the whole) of the plugin to fix everything. I'm moving the Model "body" to pure JSON object processing, then no mode mongoose / MongoDB versions problems for a while.

Still have some cases not passing. I hope to finish them soon and release a new version.

**Comment by nassor** [comment]
Update hook wasn't saving a document since the first implementation. Why? The Mongoose library into the:

- pre-hook: return only the update action. `_update: { '$set': { updatedFor: 'Tester' } },`
- post hook: return the resulting hash: `{ result: { ok: 1, nModified: 1, n: 1 }`

That makes impossible save the document before an update.

I'm removing this (no-)functionality on the next release.
